# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

schedules:
- cron: "0 7 * * *"
  displayName: Daily seven build
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'
#  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm install -g gatsby-cli
  displayName: 'install gatsby client'

- script: |
    gatsby build
  displayName: 'gatsby build'

- task: CopyFiles@2
  inputs:
    Contents: 'public/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
